# Generated by Django 5.1.6 on 2025-02-23 17:13

import datetime
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('image', models.ImageField(upload_to='images/')),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('section', models.CharField(choices=[('Popular', 'Popular'), ('Recent', 'Recent'), ('Trending', 'Trending'), ('Latest Post', 'Latest Post')], max_length=100)),
                ('main_post', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, choices=[('P', 'primary'), ('S', 'success'), ('D', 'danger'), ('W', 'warning')], max_length=1, null=True)),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='accounts.profile')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.category')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
