# Generated by Django 5.1.6 on 2025-02-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.TextField(blank=True, null=True),
        ),
    ]
